import { Router, type IRouter } from "express";
import healthRouter from "./health";
import cutsRouter from "./cuts";
import statsRouter from "./stats";
import tipsRouter from "./tips";
import subscribeRouter from "./subscribe";
import jobOutlookRouter from "./job-outlook";
import newsRouter from "./news";
import rssRouter from "./rss";
import sitemapRouter from "./sitemap";
import digestRouter from "./digest";
import alertsRouter from "./alerts";
import intelligenceRouter from "./intelligence";
import talentRouter from "./talent";
import authRouter from "./auth";
import warnRouter from "./warn";
import skillsGapRouter from "./skills-gap";
import ogRouter from "./og";

const router: IRouter = Router();

router.use(healthRouter);
router.use(cutsRouter);
router.use(statsRouter);
router.use(tipsRouter);
router.use(subscribeRouter);
router.use(jobOutlookRouter);
router.use(newsRouter);
router.use(rssRouter);
router.use(sitemapRouter);
router.use(digestRouter);
router.use(alertsRouter);
router.use(intelligenceRouter);
router.use(talentRouter);
router.use(authRouter);
router.use(warnRouter);
router.use(skillsGapRouter);
router.use(ogRouter);

export default router;
